networks:
  helperflow:

services:

  api:
    container_name: helperflow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/helperflow
    networks:
      - helperflow